model:
  base_model: distilbert-base-uncased
  dropout: 0.1
  fusion: null
project_name: JengaAI_NER_Experiment
tasks:
- data_path: /Users/naynek/Desktop/MultiClassifier/Jenga-AI/examples/ner_synthetic_dataset_v1.jsonl
  heads:
  - name: ner_head
    num_labels: 10
    weight: 1.0
  label_maps:
    ner_head:
      0: AGE
      1: GENDER
      2: INCIDENT_TYPE
      3: LANDMARK
      4: LOCATION
      5: NAME
      6: O
      7: PERPETRATOR
      8: PHONE_NUMBER
      9: VICTIM
  labels: null
  name: SwahiliNER
  type: ner
tokenizer:
  max_length: 256
  pad_token_id: 0
  padding: max_length
  truncation: true
training:
  batch_size: 8
  device: cpu
  early_stopping_patience: 3
  eval_strategy: epoch
  greater_is_better: false
  learning_rate: 2.0e-05
  load_best_model_at_end: true
  logging:
    experiment_name: JengaAI_NER
    service: mlflow
    tracking_uri: null
  metric_for_best_model: eval_loss
  num_epochs: 5
  output_dir: ./unified_results_ner
  save_strategy: epoch
  warmup_steps: 100
  weight_decay: 0.01
